### ISSUE TITLE
relmongo improvement

### ISSUE THREAD

**Issue by halimpuckjava** [kaiso/relmongo#28] opened 2018-08-19 09:42 UTC
hi

its work (i forgot to instantiate list cars in person document) however after persistence data , in mongodb car document have no info about owner (no reference for person in car document) 

![sans titre](https://user-images.githubusercontent.com/20538231/44307564-a26fcc80-a3a4-11e8-92ae-8aa48ec758fe.jpg)

**Comment by kaiso** [comment] 2018-08-19 12:38
hello,

it’s normal, that’s the philosophy of the mappedBy, the relation is persisted in the database only in one side, RelMongo is able to retrieve both sides of the bidirectional relation using only the reference in one side. 

So it’s not a bug.

**Comment by halimpuckjava** [comment] 2018-08-19 19:28
hi

1. i know and i not said its a bug, just i want how can ref the first side (person) from second side  (car) of relationship (ref person from car in our exemple its always NULL),

2. whit in hibernate sql database (expmemple : mysql) work fine (in car table i have the primary key of person as foreign key) whats deff with mongodb ??

**Comment by kaiso** [comment] 2018-08-19 20:39
hi, 
in hibernate if you have the reference in car table with foreign key, you do not have the reference in the person table, the reference is only persisted in one side. so it's the same .

if you have other questions please close this issue and join chat on gitter (https://gitter.im/relmongo/general), I will be pleased to answer your questions, and only submit issues when they are really ones.

FYI: I also released a new version 2.2.0-RC2 of RelMongo with minor bug fixes

**Closed** 2018-08-20 09:12 UTC
